#!/usr/bin/ruby -w
#
# Slothbot
#

require_relative 'lib/slothbot'

DEFAULT_PHRASES = [
  "stop him in his tracks, show him that i am ruthless",
  "time to pay the piper",
  "this is the season to let the real motherfuckin gs in",
  "boy you should've known by now",
  "approach me like you hard, motherfucker i'm gonna bank you",
  "i never met an og who never did shit wrong",
  "claiming my city, but dre, you ain't from compton",
  "this is going out to your studio gangsters",
  "never ever once have you ran with the turf",
  "smoother then a bitch but portray the role of gangster",
]

server  = 'chat.freenode.net'
channel = '#slothkrew'
nick    = 'slothbot'
phrases = DEFAULT_PHRASES

def load_phrases(path)
  File.open(path, 'r') do |file|
    phrases = file.read.strip.lines
  end
end

ARGV.each_with_index do |arg, i|
  arg == '-s' ? server = ARGV[i+1] : server
  arg == '-c' ? channel = "##{ARGV[i+1]}" : channel
  arg == '-n' ? nick = ARGV[i+1] : nick
  arg == '-p' ? phrases = load_phrases(ARGV[i+1]) : phrases
end

slothbot = Slothbot::Bot.new do
  configure do |c|
    c.nick = nick
    c.user = nick
    c.server = server
    c.port = 6697
    c.ssl.use = true
    c.channels = [channel]
    c.plugins.plugins = [Slothbot::Plugins::Blurt]
    c.plugins.options[Slothbot::Plugins::Blurt] = {
      :phrases => phrases
    }
  end
end

slothbot.start

