#!/usr/bin/ruby -w
#
# Slothbot
#

require_relative 'lib/slothbot'

def load_phrases(path)
  File.open(path, 'r').read.strip.each_line.collect do |line|
    line.strip!
		line if ! line.empty? and line[0] != '#'
  end
end

server  = 'chat.freenode.net'
channel = '#slothkrew'
nick    = 'slothbot'
phrases = load_phrases 'eazy_e.txt'

ARGV.each_with_index do |arg, i|
  arg == '-s' ? server = ARGV[i+1] : server
  arg == '-c' ? channel = "##{ARGV[i+1]}" : channel
  arg == '-n' ? nick = ARGV[i+1] : nick
  arg == '-p' ? phrases = load_phrases(ARGV[i+1]) : phrases
end

slothbot = Slothbot::Bot.new do
  configure do |c|
    c.nick = nick
    c.user = nick
    c.server = server
    c.port = 6697
    c.ssl.use = true
    c.channels = [channel]
    c.plugins.plugins = [
      Slothbot::Plugins::Currency,
      Slothbot::Plugins::Blurt,
    ]
		c.plugins.options[Slothbot::Plugins::Blurt] = {
			:phrases => phrases
		}
  end
end

slothbot.start

